[webserver]
port = 8888

[logging]
level = 5 #Debug

[database]
username = "root"
password = "hari@1234"
dbname = "shopinglist"
ip = "localhost"
port = 3306
max_connection_attempt = 60

[kv]
#ip = "redis"
ip = "127.0.0.1:9675"